### ISSUE TITLE
UnitfulMatrix: Operations like `sum`, `mean` don't carry units

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/UnitfulLinearAlgebra.jl#51]
For Unitful vectors, I can perform sums and use methods from the Statistics library easily. These same methods don't carry units with UnitfulMatrix types. Is this the intended behavior? Here's an example with `sum`, but the same thing happens for `mean`
```
julia> using Unitful, UnitfulLinearAlgebra

julia> m = u"m" 
m

julia> data = [1m, 2m, 3m]
3-element Vector{Quantity{Int64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}:
 1 m
 2 m
 3 m

julia> sum(data)
6 m

julia> sum(UnitfulMatrix(data))
6
```

**Comment by ggebbie** [comment]
merged https://github.com/ggebbie/UnitfulLinearAlgebra.jl/pull/53

not sure it is worth the added Statistics dependency

I may try changing `getindex` to get these functions for free but I am afraid of the consequences elsewhere.

**Comment by b-r-hamilton** [comment]
I started writing some little helper functions to do this in my code, so either way is fine with me. I could imagine myself using `mean` a lot though (here was using it to remove a mean before doing an EOF)
