### ISSUE TITLE
significance of `unitrange` returning row vector vs. column vector

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/UnitfulLinearAlgebra.jl#82]
I have an UnderdeterminedProblem I'm trying to solve with BLUEs, and I think I have all the arguments with the exact same dimensions/domains/ranges as a previous problem that I could solve with no errors. However, now, I'm throwing a "matrices not dimensionally conformable for addition" error at line 320 in the BLUEs.jl, which is 

```
    Cyy = up.E*Cxy + up.Cnn
```
The only difference I can find between my arguments for the problems is that, in the new problem, `unitrange(Cnn)` returns a row vector instead of a column vector, as it does in the problem I could solve successfully. The row vector is equal to the transpose of the column vector however. Is there any significance to this? The `show()` of the two `Cnn` matrices has values + units as I would expect. 

I also could be totally barking up the wrong tree here.

**Comment by ggebbie** [comment]
sounds like an error in the code.  `unitdomain` and `unitrange` should have been designed to be regular (column) vectors. Is this a standard case? If not, please show how to produce a "bad" Cnn.

**Comment by b-r-hamilton** [comment]
I did it by multiplying by a non-unitful matrix, perhaps this just shouldn't be done, but it's definitely a mistake I'd make again 

```
julia> using Unitful, UnitfulLinearAlgebra

julia> K = u"K"
K

julia> mat1 = UnitfulMatrix(randn((5,5))K)
5×5 UnitfulMatrix{Float64,2}
  0.802641 K  -0.477889 K     -1.8004 K   1.03946 K   0.832787 K
  0.305566 K    1.26118 K    -0.50176 K  0.573131 K  0.0388594 K
  0.499757 K   0.820694 K  -0.0913419 K   1.55333 K   -1.11427 K
 -0.968852 K    1.36814 K    0.141891 K   1.67554 K    1.07575 K
  0.849992 K   0.123954 K    0.520606 K  -1.26443 K   0.456499 K

julia> unitrange(mat1)
Units Categorical{Unitful.FreeUnits} Unordered
wrapping: 5-element Vector{Unitful.FreeUnits}:
 K
 K
 K
 K
 K

julia> mat2 = randn((5,5)) * mat1
5×5 UnitfulMatrix{Float64,2}
   -2.04782 K  -0.432458 K    1.17148 K    1.17772 K  0.270587 K
   -1.04421 K  -0.882586 K  -0.482815 K    -2.0059 K   1.94035 K
 -0.0160068 K   0.876712 K   0.271024 K  -0.321959 K  0.662059 K
  -0.557216 K    1.39362 K   0.104656 K    2.55563 K   1.34603 K
   0.662366 K    4.02594 K  -0.510111 K     2.2963 K  0.902875 K

julia> unitrange(mat2)
Units Unitful.FreeUnits{(K,), 𝚯, nothing}[K, K, K, K, K]

julia> unitdomain(mat2)
Units Categorical{Unitful.FreeUnits} Unordered
wrapping: 5-element Vector{Unitful.FreeUnits}:
 
 
 
 
 

julia> 
```
I managed to get my code working now by redefining `Cnn` matrix so that the units line up with the output of `up.E*Cxy`, but there's definitely something I still don't understand, because that forced me to have different units from my original case that also works... I was thinking maybe it would be nice to have, perhaps somewhere in BLUEs, a generic guideline to what the unitdomain and unitrange of each argument to a Problem should be, because this is the second time I've burned up over an hour fighting with the units (or maybe I should just write a guide for myself!)

**Comment by b-r-hamilton** [comment]
Okay this all makes sense! I wasn't actually calling `size` on the unitdims, just going off the REPL-show, which is probably a good lesson to not take that at face value. 

That makes sense about the Cnn, for some reason I have an older script where Cnn is not in that form (has all units on the range, but it still works... Need to look more into what's going on there), which was not helping my confusion this morning. Do you think that there should be a warning or error if you try to provide a Cnn that does not have `unitrange .== unitdomain .^-1`, or is that too constraining? 

The unitless matrix times Unitful matrix is just coming from trying to multiply the SVD U, $\Sigma$ into the problem (has to multiply y, and Cnn) - I had just assumed if I did that multiplication, the units would work out fine, but that was evidently not case.

**Comment by ggebbie** [comment]
Great idea to include a warning!  There is already a Boolean operator that will help for this purpose:
https://ggebbie.github.io/UnitfulLinearAlgebra.jl/dev/#UnitfulLinearAlgebra.unit_symmetric-Tuple{UnitfulLinearAlgebra.AbstractUnitfulType}

Are you using the function `svd` with a UnitfulMatrix or the dimensional singular value decomposition `dsvd`?   Here is the documentation for dsvd. It's not the same as the SVD but it is more relevant for matrices with units.

https://ggebbie.github.io/UnitfulLinearAlgebra.jl/dev/#UnitfulLinearAlgebra.dsvd-Tuple{AbstractUnitfulVecOrMat{T,%202}%20where%20T,%20AbstractUnitfulVecOrMat{T,%202}%20where%20T,%20AbstractUnitfulVecOrMat{T,%202}%20where%20T}

https://ggebbie.github.io/UnitfulLinearAlgebra.jl/dev/#UnitfulLinearAlgebra.DSVD

You could use identity matrices for the numerical part of the norm matrices that go into `dsvd`.

**Comment by b-r-hamilton** [comment]
I'm doing the SVD on a water mass composition matrix, so it is unitless, and I'm just doing LinearAlgebra.SVD on a regular matrix. Would that be your recommendation for a problem with a lot of Unitful matrices elsewhere, or do you think I should do the ULA.SVD on a Unitful matrix with no units?

**Comment by ggebbie** [comment]
Neither. My (surprising) recommendation is to use the Dimensional Singular Value Decomposition (`UnitfulLinearAlgebra.dsvd`).

Some background points:
1. With a dimensionless matrix, the SVD exists. There is nothing wrong with using the SVD.

2. If I understand your case correctly, you have a dimensionless matrix but the unit domain and unit range have dimensions. In other words, your original matrix accepts uniform vectors (with units) in multiplication. Both the unit domain and range are uniform with the same units, which gives you a dimensionless matrix. A dimensionless matrix is also a uniform matrix, where there is uniformly "no units" everywhere in the matrix. For a uniform matrix, you have the option of taking the SVD or the Dimensional Singular Value Decomposition.

3. The SVD and the DSVD are different when the unit domain and unit range have dimensions. The difference is in how the units are distributed amongst the three components of the decomposition.

Taking the SVD, you will get U, Lambda, and V are all dimensionless.

Taking the DSVD, you will get a uniform U with units equal to the reciprocal of the unit domain, Lambda is dimensionless, and V has units equal to the unit domain. 

Why Dimensional SVD here?   In this particular problem, I believe you are using the right singular vectors (V) has a basis set. Using the DSVD, the right singular vectors will naturally have the units of the input of the matrix of interest. Therefore, a quantity like `V*u`, where `u` is a control vector that you are solving for, will allow you to have a dimensionless u. All of the necessary units are taken care of by `V`. 

Why try to solve for a `u` that is dimensionless?  Optimization routines typically work best when they are solving for a normalized variable, like a series of independent and identically distributed variables. When variables have units, this normalization step must account for the units as well. After normalization, all units are removed. 

There are downsides to this approach as well. Extra arguments have to be passed to the `dsvd` routine relative to `svd`. Here is one way to do a simple `dsvd`.

```julia
using Unitful, UnitfulLinearAlgebra, LinearAlgebra
urange = [u"K",u"K"]
udomain = [u"K",u"K",u"K"]
A = UnitfulMatrix(randn(length(urange),length(udomain)),urange,udomain)
Pr = UnitfulMatrix(I(length(urange)),urange.^-1,urange)
Pd = UnitfulMatrix(I(length(udomain)),udomain.^-1,udomain)
U,Λ,V = dsvd(A,Pr,Pd)
```
